name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    name: "python ${{ matrix.python-version }} ${{ matrix.toxenv }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9]
        toxenv: [""]
        experimental: [ false ]
        include:
          - toxenv: qa
            python-version: 3.7
            experimental: false
          - toxenv: type
            python-version: 3.7
            experimental: false
          - experimental: true
            python-version: "3.10.0-beta.2 - 3.10"
          - experimental: true
            python-version: "pypy-3.7"


    continue-on-error: ${{ matrix.experimental }}
    env:
      TOXENV: ${{ matrix.toxenv }}
    steps:
      # chrome headless
      - uses: browser-actions/setup-chrome@latest
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system deps
        run: >-
          sudo apt-get install libgirepository1.0-dev \
            libcairo2-dev \
            pkg-config \
            python3-dev \
            gir1.2-gtk-3.0 \
            gcc \
            fontconfig

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox python-coveralls codecov
      - name: Run tests
        run: tox

      - name: 'Save image regression report'
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: image_diff
          path: tests/.tests/image_diff/
          retention-days: 5

      - uses: codecov/codecov-action@v1
        with:
          env_vars: OS,PYTHON,TOXENV